language: java
sudo: false
install: true
dist: trusty

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: islomar-github
    token: $SONARCLOUD_TOKEN

jobs:
  include:
    - stage: isolated tests
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
      after_success:
        - mvn test jacoco:report coveralls:report

    - stage: sociable tests
      script:
        - mvn clean test -PintegrationTests

    - stage: end to end tests
      script:
        - mvn clean test -Pend2end

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
